// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdvnDvuvXp863NWLkVuXmMSkALrkywhmw',
    appId: '1:672838071338:android:cc1629dacaa4d44c2a3f53',
    messagingSenderId: '672838071338',
    projectId: 'todo-list-app-76d0c',
    storageBucket: 'todo-list-app-76d0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLvNXXcy85N1udjY1RmFG7i95o9Now0L8',
    appId: '1:672838071338:ios:7bb68d15ab7bb49b2a3f53',
    messagingSenderId: '672838071338',
    projectId: 'todo-list-app-76d0c',
    storageBucket: 'todo-list-app-76d0c.appspot.com',
    androidClientId: '672838071338-f6ghoecsr4sm2j7rrveuo9d1od9dqspd.apps.googleusercontent.com',
    iosClientId: '672838071338-ec1niuh65q060pgn8m9i1la9lbj7p1m0.apps.googleusercontent.com',
    iosBundleId: 'br.dev.andresimoes.todoListApp',
  );
}
